### ISSUE TITLE
support using instance metadata for S3 access

### ISSUE THREAD

**Issue by mbainter** [chef-cookbooks/supermarket-omnibus-cookbook#65]
### Cookbook version
3.0.0

### Chef-client version
15.1.36

### Platform Details
Ubuntu 16 on AWS

### Scenario:
Chef Supermarket running on an AWS instance and configured to use S3 for storage.  The S3 bucket is configured with an appropriate bucket policy, limiting access to its contents to the AWS account, with the "Block all public access" bucket-level option selected. 

### Expected Result:
Chef supermarket should still be able to write new versions of cookbooks and new cookbooks.

### Actual Result:
Chef supermarket fails to accept new cookbooks.

When using stove or knife it fails.  

<details>
<summary>Stove output:</summary>
<p>

```
Making tarball xmpp_role.tgz
DEBUG: Signing: method: post, url: https://supermarket.internal-domain.com/api/v1/cookbooks, file: #<File:0x0000000007278e48>, User-id: mbainter, Timestamp: 2019-07-30T22:54:39Z
ERROR: Error uploading cookbook my_cookbook to Supermarket: parse error: trailing garbage
                                          500 Internal Server Error If you ar
                            (right here) ------^
       . Increase log verbosity (-VV) for more information.
TRACE:
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/json_compat.rb:35:in `rescue in parse'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/json_compat.rb:32:in `parse'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/json_compat.rb:40:in `from_json'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/knife/supermarket_share.rb:132:in `do_upload'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/knife/supermarket_share.rb:96:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/knife.rb:475:in `block in run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/knife.rb:474:in `run_with_pretty_exceptions'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/knife.rb:222:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/lib/chef/application/knife.rb:162:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/chef-15.1.36/bin/knife:24:in `<top (required)>'
/opt/chefdk/bin/knife:319:in `load'
/opt/chefdk/bin/knife:319:in `<main>'
```

</p>
</details>

<details>
<summary>supermarket log</summary>
<p>

```
2019-07-30_22:54:40.14765 F, [2019-07-30T22:54:40.147561 #318] FATAL -- : [044c306a-da02-436f-8655-f3fa7f2ba733]
2019-07-30_22:54:40.14786 F, [2019-07-30T22:54:40.147826 #318] FATAL -- : [044c306a-da02-436f-8655-f3fa7f2ba733] Aws::S3::Errors::AccessDenied (Access Denied):
2019-07-30_22:54:40.14800 F, [2019-07-30T22:54:40.147959 #318] FATAL -- : [044c306a-da02-436f-8655-f3fa7f2ba733]
2019-07-30_22:54:40.14814 F, [2019-07-30T22:54:40.148105 #318] FATAL -- : [044c306a-da02-436f-8655-f3fa7f2ba733] app/models/cookbook.rb:301:in `block in publish_version!'
2019-07-30_22:54:40.14820 [044c306a-da02-436f-8655-f3fa7f2ba733] app/models/cookbook.rb:274:in `publish_version!'
2019-07-30_22:54:40.14824 [044c306a-da02-436f-8655-f3fa7f2ba733] app/models/cookbook_upload.rb:37:in `block in finish'
2019-07-30_22:54:40.14829 [044c306a-da02-436f-8655-f3fa7f2ba733] app/models/cookbook_upload.rb:36:in `tap'
2019-07-30_22:54:40.14834 [044c306a-da02-436f-8655-f3fa7f2ba733] app/models/cookbook_upload.rb:36:in `finish'
2019-07-30_22:54:40.14839 [044c306a-da02-436f-8655-f3fa7f2ba733] app/controllers/api/v1/cookbook_uploads_controller.rb:48:in `create'
2019-07-30_22:54:40.14977 W, [2019-07-30T22:54:40.149726 #318]  WARN -- : [044c306a-da02-436f-8655-f3fa7f2ba733] Can't verify CSRF token authenticity.
2019-07-30_22:54:40.15014 Error during failsafe response: ActionController::InvalidAuthenticityToken
```

</p>
</details>

If I clear the "Block public access" option, stove can push cookbooks successfully.

**Comment by mbainter** [comment]
Oops, should've opened this in the supermarket repository.
